# Generated by Django 2.1.5 on 2019-03-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
