# Generated by Django 2.1.5 on 2019-02-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionexercise',
            name='course_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.CourseSession'),
        ),
    ]
