# Generated by Django 2.1.5 on 2019-03-02 20:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0010_auto_20190219_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesessionexercise',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
