# Generated by Django 2.1.5 on 2019-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0021_auto_20190404_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionexercise',
            name='aparat_video',
            field=models.TextField(null=True),
        ),
    ]
