# Generated by Django 2.1.5 on 2019-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_auto_20190219_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
