# Generated by Django 2.1.5 on 2019-04-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0023_auto_20190404_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='prev_session',
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='next_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_se', to='app_base.CourseSession'),
        ),
    ]
