# Generated by Django 2.1.5 on 2019-02-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0009_auto_20190219_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
