# Generated by Django 2.1.5 on 2019-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_auto_20190302_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
