# Generated by Django 2.1.5 on 2019-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aducation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دانش\u200cآموزش'), (2, 'دیپلم'), (3, 'دانشجو'), (4, 'کاردانی'), (5, 'کارشناسی'), (6, 'کارشناسی ارشد'), (7, 'دکتری')]),
        ),
    ]
