# Generated by Django 2.1.5 on 2019-02-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_auto_20190211_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '---'), (1, 'دانش\u200cآموزش'), (2, 'دیپلم'), (3, 'دانشجو'), (4, 'کاردانی'), (5, 'کارشناسی'), (6, 'کارشناسی ارشد'), (7, 'دکتری')], null=True),
        ),
    ]
