# Generated by Django 2.1.5 on 2019-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0006_auto_20190219_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesessionexercise',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
