# Generated by Django 2.1.5 on 2019-03-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_chatwithus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatWithUs',
            new_name='Ticket',
        ),
    ]
