# Generated by Django 2.1.5 on 2019-03-16 13:59

import app_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_accounts.models.avatar_path),
        ),
    ]
