# Generated by Django 2.1.5 on 2019-03-21 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_auto_20190302_2010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0010_auto_20190321_0437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredCourse',
            new_name='RegisteredItem',
        ),
    ]
