# Generated by Django 2.1.5 on 2019-02-09 17:30

import app_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_auto_20190209_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=app_base.models.course_image_path),
        ),
    ]
