# Generated by Django 2.1.5 on 2019-04-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0017_auto_20190403_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisebystudent',
            name='done',
        ),
    ]
