# Generated by Django 2.1.5 on 2019-04-04 08:13

import app_base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0022_coursesessionexercise_aparat_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='next_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_se', to='app_base.CourseSession'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='prev_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_se', to='app_base.CourseSession'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=app_base.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='coursesessionexercise',
            name='aparat_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
