# Generated by Django 2.1.5 on 2019-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0013_auto_20190402_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
