# Generated by Django 2.1.5 on 2019-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_auto_20190219_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
