# Generated by Django 2.1.5 on 2019-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0006_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
