# Generated by Django 2.1.5 on 2019-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
