# Generated by Django 2.1.5 on 2019-04-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0018_remove_exercisebystudent_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisebystudent',
            name='rate',
        ),
        migrations.AddField(
            model_name='exercisebystudent',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisebystudent',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
