# Generated by Django 2.1.5 on 2019-03-09 14:06

import app_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0006_auto_20190219_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دانش\u200cآموزش'), (2, 'دیپلم'), (3, 'دانشجو'), (4, 'کاردانی'), (5, 'کارشناسی'), (6, 'کارشناسی ارشد'), (7, 'دکتری')], null=True, validators=[app_accounts.models.check_education], verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه'),
        ),
    ]
