# Generated by Django 2.1.5 on 2019-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0012_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
