# Generated by Django 2.1.5 on 2019-04-03 15:53

import app_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0015_coursesession_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionexercise',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesessionexercise',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='video',
            field=models.FileField(null=True, upload_to=app_base.models.get_upload_path),
        ),
    ]
