# Generated by Django 2.1.5 on 2019-04-04 10:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0026_auto_20190404_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
