# Generated by Django 2.1.5 on 2019-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0007_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
