# Generated by Django 2.1.5 on 2019-04-02 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0008_ticket_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='create_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
