# Generated by Django 2.1.5 on 2019-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_chat_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
