# Generated by Django 2.1.5 on 2019-03-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0007_auto_20190309_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='asd'),
        ),
    ]
